services:
  notebook-milvus:
    image: jupyter-milvus
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notebook-milvus
    ports:
      - "8888:8888"
    env_file:
      - .env